### 1. User and Role Management

### API 1 User Registration  - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "role":"ADMIN",
    "status":"active"
}




### API 2 User Register Missing Name   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "role":"ADMIN",    
    "status":"active"
}


### API 3 User Register Missing Email  - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",   
    "password":"premkumar45",
    "role":"ADMIN",
    "status":"active"

}


### API 4 User Register Missing Password  - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",   
    "role":"ADMIN",
    "status":"active"

}

### API 5 User Register Missing Role   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "status":"active"

}


### API 6 User Register Invalid Role   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "role":"INVALIDROLE",
    "status":"active"
}




### API 18 User Register Missing Status   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "role":"ADMIN"
    
}


### API 19 User Register Invalid Status   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "role":"ADMIN",
    "status":"shdfkhsakf"
}





### API 7 User Register Weak Password   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"week",
    "role":"ADMIN"
}



### API 8 User Register Invalid Email Format    - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "name":"Prem Kumar",
    "email":"premkumarjp45ssscasgjfd",
    "password":"premkakkkssk",
    "role":"ADMIN"
}




### API 9 User Register User Duplicate Email   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
        "name":"Prem Kumar",
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45",
    "role":"ADMIN"
}





### API 10 User Register User Empty  Body   - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{

}



### API 11 User Login Success - completed
POST http://localhost:5000/api/user/register
Content-Type:application/json

{
    "email":"premkumarjp45@gmail.com",
    "password":"premkumar45"
}



### API 12 User Login (Empty  Body) - completed
POST http://localhost:5000/api/user/login
Content-Type:application/json

{

}



### API 13 User Login Missing Email  - completed
POST http://localhost:5000/api/user/login
Content-Type:application/json

{

    "password":"premkumar45"
}


### API 14 User Login Missing Password - completed
POST http://localhost:5000/api/user/login
Content-Type:application/json

{
    "email":"premkumarjp45@gmail.com"
   
}

### API 15 User Login Email Invalid Format -completed
POST http://localhost:5000/api/user/login
Content-Type:application/json

{
    "email":"premkumaskdakhsdkashkfh",
    "password":"premkumar45"
   
}


### API 16 User Login Invalid User - completed
POST http://localhost:5000/api/user/login
Content-Type:application/json

{
    "email":"premkumas@gamil.com",
    "password":"premkumar45"
   
}



### API 17 User Login Incorrect Password - completed
POST http://localhost:5000/api/user/login
Content-Type:application/json

{
   "email":"premkumarjp45@gmail.com",
    "password":"premkumar45dasdasddasfad"
   
}





### 2. Financial Records Management

### API 1 Create Record with Admin -- completed
http://localhost:5000/api/finance/create-record
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByZW1rdW1hcmpwNDVAZ21haWwuY29tIiwiaWF0IjoxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA
Content-Type: application/json

{
  "amount": 5000,
  "type": "INCOME",
  "category": "SALARY",
  "description": "Monthly salary"
}

### API 2 Create Record Invalid Admin JWT TOKEN --completed
http://localhost:5000/api/finance/create-record
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI

{
  "amount": 5000,
  "type": "INCOME",
  "category": "SALARY",
  "description": "Monthly salary"
}

### API 3 Create  record with Admin -- Missing Amount -- completed
http://localhost:5000/api/finance/create-record
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByZW1rdW1hcmpwNDVAZ21haWwuY29tIiwiaWF0IjoxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA
Content-Type: application/json

{
  
  "type": "INCOME",
  "category": "SALARY",
  "description": "Monthly salary"
}


### API 4 Create  record with Admin -- Missing Type --completed
http://localhost:5000/api/finance/create-record
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByZW1rdW1hcmpwNDVAZ21haWwuY29tIiwiaWF0IjoxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA
Content-Type: application/json

{
  
  "amount": 5000,
  "category": "SALARY",
  "description": "Monthly salary"
}



### API 5 Create  record with Admin -- Missing Category --completed
http://localhost:5000/api/finance/create-record
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByZW1rdW1hcmpwNDVAZ21haWwuY29tIiwiaWF0IjoxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA
Content-Type: application/json

{
  "amount": 5000,
  "type": "INCOME",
  "description": "Monthly salary"
}

### API 6 Create  record with Admin -- Missing Description --completed
http://localhost:5000/api/finance/create-record
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByZW1rdW1hcmpwNDVAZ21haWwuY29tIiwiaWF0IjoxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA
Content-Type: application/json

{
  "amount": 5000,
  "type": "INCOME",
  "category": "SALARY"
}




### API 7 View All Records -completed
GET http://localhost:5000/api/finance/records
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InByZW1rdW1hcmpwNDVAZ21haWwuY29tIiwiaWF0IjoxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA


### API 8 View All Records Missing Token  --completed
GET http://localhost:5000/api/finance/records



### API 9 View All Records Invalid Token  -completed
GET http://localhost:5000/api/finance/records
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.oxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA



### API 10 Sigle View Record with record Id  Can view Admin & Analyst  -completed
GET http://localhost:5000/api/finance/record/69d28f8d5da49ab2d36a0524
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.oxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA

### API 11 Sigle View Record with Invalid record Id  Can view Admin & Analyst  -completed
GET http://localhost:5000/api/finance/record/69d28f8d5da49ab2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.oxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA


### API 12 Sigle View Record with record Id without JWT TOKEN -completed
GET http://localhost:5000/api/finance/record/69d28f8d5da49ab2




### API 13 Sigle View Record with record id with Viewer get Failed -completed
GET http://localhost:5000/api/finance/record/69d28f8d5da49ab2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.oxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA




### API 14 Record Update with record Id  - Only Admin  --completed
PUT http://localhost:5000/api/finance/record/69d28f8d5da49ab2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.oxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA


### API 15 Record Update with record Id  - Only Admin  --completed-Without Jwt Failed
PUT http://localhost:5000/api/finance/record/69d28f8d5da49ab2


/*/
  "amount": 5000,
  "type": "INCOME",
  "category": "SALARY",
  "description": "Monthly salary"
/*/


### API 16 Record Update Amount with record Id   - Only Admin  --completed
PUT http://localhost:5000/api/finance/record/69d28f8d5da49ab2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.oxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA
Content-Type:application/json
{
  "amount":6000
}



### API 17 Record Update Type with record Id   - Only Admin  --completed
PUT http://localhost:5000/api/finance/record/69d28f8d5da49ab2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.oxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA
Content-Type:application/json
{
 "type": "EXPENSE"
}



### API 18 Record Update Category with record Id   - Only Admin  --completed
PUT http://localhost:5000/api/finance/record/69d28f8d5da49ab2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.oxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA
Content-Type:application/json
{"category": "SALARY"
}


### API 18 Record Update Description with record Id   - Only Admin  --completed
PUT http://localhost:5000/api/finance/record/69d28f8d5da49ab2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.oxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA
Content-Type:application/json
{
  "description": "Monthly salary"

}





### API 19 Delete Record -- Only Admin 
DELETE http://localhost:5000/api/finance/record/69d28f8d5da49ab2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.oxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA



### API 20 Delete Record -- Only Admin - Without JWT TOKEN  
DELETE http://localhost:5000/api/finance/record/69d28f8d5da49ab2



### API 21 Delete Record -- Only Admin  - Invalid JWT Token 
DELETE http://localhost:5000/api/finance/record/69d28f8d5da49ab2
Authorization: Bearer eyJhbGciOiJIUzI1NiIs



### API 22 Delete Record -- Only Admin - Non Admin Access 
DELETE http://localhost:5000/api/finance/record/69d28f8d5da49ab2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.oxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA




### API 23 Filter Records Type -- Only Admin
GET http://localhost:5000/api/finance/filter-records?type=INCOME
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.oxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA



### API 24 Filter Records Category -- Only Admin
GET http://localhost:5000/api/finance/filter-records?category=FOOD
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.oxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA


### API 24 Filter Records startDate && endDate -- Only Admin
GET http://localhost:5000/api/finance/filter-records?startDate&endDate
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.oxNzc1Mzg3NjE3fQ.DOhd5EbajLGCUrp8C25coj4W8U4_hH1KMn-7ZxKUFRA


